require("ven.plugins-setup")
require("ven.core.options")
require("ven.core.keymaps")
require("ven.core.colorscheme")
require("ven.plugins.comment")
require("ven.plugins.nvim-tree")
require("ven.plugins.lualine")
require("ven.plugins.telescope")
require("ven.plugins.nvim-cmp")
require("ven.plugins.lsp.mason")
require("ven.plugins.lsp.lspsaga")
require("ven.plugins.lsp.lspconfig")
require("ven.plugins.lsp.null-ls")
require("ven.plugins.autopairs")
require("ven.plugins.treesitter")
require("ven.plugins.gitsigns")
require("ven.plugins.harpoon")
-- to make remove bg from nvim (transparent using iterm2)
vim.cmd("hi Normal guibg=000000")
